name: NetherPortalProtection
version: '${project.version}'
main: me.lagggpixel.netherportalprotection.Main
api-version: '1.20'
authors: [Lagggpixel]
description: Nether portal prevention
softdepend:
  - PlaceholderAPI
commands:
  netherportalprotection:
    description: Reload the plugin configuration
    usage: /netherportalprotection reload
    permission: netherportalprevention.reload

permissions:
  netherportalprevention.reload:
    description: Allows the player to reload plugin configurations
    default: op